[project]
name = "cablewatch"
version = "0.0.1"
description = ""
authors = [
    {name = "Sébastien MATZ",email = "loghaan@gmail.com"}
]
readme = "README.rst"
requires-python = ">=3.13,<3.14"
dependencies = [
    "sphinx (>=9.1.0,<10.0.0)",
    "sphinx-rtd-theme (>=3.1.0,<4.0.0)",
    "myst-parser (>=5.0.0,<6.0.0)",
    "sphinx-revealjs (>=3.2.1,<4.0.0)",
    "sphinx-gizeh @ git+https://gitlab.com/loghaan/sphinx-gizeh.git@871c4979bb53a0c0b82204dfe0934d2cdd46cf3e",
    "aiohttp (>=3.13.2,<4.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "psutil (>=7.1.3,<8.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "bs4 (>=0.0.2,<0.0.3)",
    "rich (>=14.2.0,<15.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-sugar (>=1.1.1,<2.0.0)",
    "ruff (>=0.14.10,<0.15.0)",
    "yt-dlp (==2025.12.08)",
    "apscheduler (>=3.11.2,<4.0.0)",
    "google-cloud-storage (>=3.7.0,<4.0.0)",
    "google-cloud-speech (>=2.35.0,<3.0.0)",
    "duckdb (>=1.4.3,<2.0.0)",
    "pytesseract (>=0.3.13,<0.5.0)",
    "strip-ansi (>=0.1.1,<0.2.0)",
    "rapidfuzz (>=3.14.3,<4.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[project.scripts]
cablewatch-super = "cablewatch.super:main"
cablewatch-download-roadmap = "cablewatch.scripts.download_roadmap:main"
cablewatch-ingest = "cablewatch.ingest:main"
cablewatch-mrproper = "cablewatch.scripts.mister_proper:main"
cablewatch-speech = "cablewatch.speech:main"
cablewatch-adduser = "cablewatch.user:main"
cablewatch-stash = "cablewatch.stash:main"
cablewatch-banners = "cablewatch.banners:main"
cablewatch-papers = "cablewatch.papers:main"
cablewatch-build-docs = "cablewatch.scripts.build_docs:main"
